name: test

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_rust:
    runs-on: ubuntu-latest
    env:
      working-directory: ./lib
    steps:
    - uses: actions/checkout@v2
    - name: Test Rust Lib
      working-directory: ${{env.working-directory}}
      run: cargo test

  build_wasm:
    needs: test_rust
    runs-on: ubuntu-latest
    env:
      working-directory: ./wasm
      wasm-file: wasm/target/wasm32-unknown-unknown/release/wasm.wasm
    steps:
    - uses: actions/checkout@v2
    - run: rustup +nightly target add wasm32-unknown-unknown
    - name: Build
      working-directory: ${{env.working-directory}}
      run: cargo build --release --target wasm32-unknown-unknown --verbose
    - name: Get Binaryen (wasm-opt)
      run: |
        wget https://github.com/WebAssembly/binaryen/releases/download/version_110/binaryen-version_110-x86_64-linux.tar.gz
        tar -xvzf binaryen-version_110-x86_64-linux.tar.gz
    - name: Optimize
      run: |
        ./binaryen-version_110/bin/wasm-opt $WASM_FILE -o $WASM_FILE --strip-debug -Oz;
      env:
        WASM_FILE: ${{env.wasm-file}}

    - uses: actions/upload-artifact@master
      with:
        name: core-wasm
        path: ${{env.wasm-file}}

  generate_wat:
    needs: build_wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wat-wasm
        run: npm install wat-wasm -g
      - uses: actions/download-artifact@master
        with:
          name: core-wasm
          path: wasm
      - name: Commit report
        run: |
          wat-wasm wasm/wasm.wasm -o deployed.wat
          git config --global user.name 'Automated WAT-WASM'
          git config --global user.email 'automated-wasm@users.noreply.github.com'
          git add deployed.wat
          git diff-index --quiet HEAD || git commit -m "Automated wat-wasm"
          git push
        