name: test

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_rust:
    runs-on: ubuntu-latest
    env:
      working-directory: ./lib
    steps:
    - uses: actions/checkout@v2
    - name: Test Rust Lib
      working-directory: ${{env.working-directory}}
      run: cargo test

  build_wasm:
    needs: test_rust
    runs-on: ubuntu-latest
    env:
      working-directory: ./wasm
      wasm-file: wasm/target/wasm32-unknown-unknown/release/wasm.wasm
    steps:
    - uses: actions/checkout@v2
    - run: rustup +nightly target add wasm32-unknown-unknown
    - name: Build
      working-directory: ${{env.working-directory}}
      run: cargo build --release --target wasm32-unknown-unknown --verbose
    - uses: actions/upload-artifact@master
      with:
        name: core-wasm
        path: ${{env.wasm-file}}